### ISSUE TITLE
Error when using `expr` predicate in `has` clause

### ISSUE THREAD

**Issue by prockenschaub** [justin13601/ACES#103]
The following semantically identical change to the in-hospital mortality example leads to an error. 

```yaml
# Task: 24-hour In-hospital Mortality Prediction
predicates:
  admission:
    code: event_type//ADMISSION
  discharge:
    code: event_type//DISCHARGE
  death:
    code: event_type//DEATH
  discharge_or_death:
    expr: or(discharge, death)

trigger: admission

windows:
  input:
    start: NULL
    end: trigger + 24h
    start_inclusive: True
    end_inclusive: True
    has:
      discharge_or_death: (None, 0)
      _ANY_EVENT: (5, None)
    index_timestamp: end
  gap:
    start: trigger
    end: start + 48h
    start_inclusive: False
    end_inclusive: True
    has:
      admission: (None, 0)
      # discharge: (None, 0)        # <- remove
      # death: (None, 0)
      discharge_or_death: (None, 0) # <- add
  target:
    start: gap.end
    end: start -> discharge_or_death
    start_inclusive: False
    end_inclusive: True
    label: death
```

I came across this while trying to create the [MEDS-DEV in-ICU](https://github.com/mmcdermott/MEDS-DEV/blob/030babe2b135633976872562a9b785cb03d0afa4/src/MEDS-DEV/tasks/criteria/mortality/in_icu/first_24h.yaml) mortality task for AUMCdb, which uses the shortcut above. 

This is not high priority but good to fix because it took me a while to figure out where in the config the error originated from.
