### ISSUE TITLE
Support for Relative Numeric Value Criteria Between Different Measurements

### ISSUE THREAD

**Issue by Oufattole** [justin13601/ACES#149]
I specifically want to be able to define a cohort where a numeric_value_criteria is applied, for example checking if a lab value is larger than the previous time it was observed. It would look something like this I think:

```yaml
predicates:
  diagnosis_event:
    code: diagnosis_b_code
  med_event:
    code: medication_a_code

trigger: med_event
windows:
  input:
    start: trigger - 30d
    end: trigger
    start_inclusive: True
    end_inclusive: False
    index_timestamp: end
    has:
      med_event:
          count: (1, None)
          numeric_value_criteria: < trigger.med_event.numeric_value - 3.25
  target:
    start: input.end
    end: start + 3m
    start_inclusive: False
    end_inclusive: True
    label: diagnosis_event
```
