### ISSUE TITLE
ACES: Incorrect label extraction with value_min predicate

### ISSUE THREAD

**Issue by Oufattole** [justin13601/ACES#156]
When using ACES with a `value_min` predicate, the label extraction appears to produce incorrect results.

## Reproduction Steps
Checkout this colab: https://colab.research.google.com/drive/1_JQL9EvmX6q6UtF72A6r12kqQqkoomKO?usp=sharing

or follow my explanation below:

1. Create a sample dataset with numeric values:
```python
data = pl.DataFrame(dict(
    subject_id=[1,1,1,1,1],
    time=[
        datetime.datetime(2000,1,1),
        datetime.datetime(2000,1,2),
        datetime.datetime(2000,1,3),
        datetime.datetime(2000,1,4),
        datetime.datetime(2000,1,5)
    ],
    code=["a", "a", "b", "b", "b"],
    numeric_value=[0.0,100.0,100.0,0.0,0.0]
))
```

2. Use the following ACES configuration:
```yaml
predicates:
  trigger_event:
    code: {regex: "a|b"}
  lab:
    code: {regex: "a|b"}
  abnormal_lab:
    code: {regex: "a|b"}
    value_min: 2.0
    value_min_inclusive: True

trigger: trigger_event

windows:
  input:
    start: NULL
    end: trigger
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
  target:
    start: input.end
    end: start + 30d
    start_inclusive: False
    end_inclusive: True
    has:
      lab: (1, None)
    label: abnormal_lab
```

3. Run ACES using the CLI:
```bash
aces-cli data.path=$data_path data.standard='meds' cohort_dir=$cohort_dir cohort_name='task_config'
```

## Expected Behavior
Based on the data and configuration with `value_min: 2.0`, we expect to see four extracted labels: True, True, False, False.

## Actual Behavior
ACES returns 4 True labels.

## Environment
- ACES version: 0.6.1
- Python version: 3.12.7

**Comment by Oufattole** [comment]
The issue is the regex, you get the expected labels if you switch from a regex to an or expression by modifying the predicates as follows:
```
predicates:
  trigger_event:
    code: {regex: "a|b"}
  lab:
    code: {regex: "a|b"}
  a_lab:
    code: a
    value_min: 2.0
    value_min_inclusive: True
  b_lab:
    code: b
    value_min: 2.0
    value_min_inclusive: True
  abnormal_lab:
    expr: or(a_lab,b_lab)
```
