### ISSUE TITLE
Directly support nested configuration files

### ISSUE THREAD

**Issue by justin13601** [justin13601/ACES#43]
- [ ] Allow nested configuration files (ie., use a config to define a more complex predicate, which can be used in a subsequent config)

**Comment by justin13601** [comment]
We aim to support nested configuration files for cohort querying, whereby the results of a particular extraction can be expressed as a predicate to inform the extraction of another cohort. This would allows users to extract cohorts for very complex and specific tasks.

**Comment by mmcdermott** [comment]
I think we should likely increase the prioritization on this, given it would be pretty transformative in terms of expressive power, and is coming up more and more in more complex tasks. We should start with a formal spec (if we want to try to build this out sooner) of how this would be defined and realized.

**Comment by mmcdermott** [comment]
A good example of the need for this is wanting to do something like have the target be a new hospitalization for a specific condition (or a hospitalization not for an elective procedure). Realizing this, we need to associate the time of the new predicate (the subsequent hospital admission) with the future data of what happens in that hospitalization, rendering it out of scope for truly static predicates.

Instead, we want something maybe like:

```
predicates:
  heart_failure_diagnosis:
    code: ??? # ICD codes for heart failure (e.g., I50.* for heart failure and subtypes)
  hospital_admission:
    code: ???
  hospital_discharge:
    code: ???

  heart_failure_hospitalization:
    trigger: hospital_admission
    windows:
      hospitalization:
        start: trigger
        end: start -> hospital_discharge
        end_inclusive: True
        start_inclusive: True
        index_timestamp: start
        has:
          heart_failure_diagnosis: (1, None) # Could use a `label` signal here instead or in addition to for non-boolean predicates.
...
```

Which would introduce a nested predicate defined to be true at the index timestamp of any valid realization of that nested config (or is defined to take the value of the extracted label with a label formulation).
