### ISSUE TITLE
Add predicates that are based on other properties or columns in MEDS event data

### ISSUE THREAD

**Issue by mmcdermott** [justin13601/ACES#87]

**Comment by mmcdermott** [comment]
This issue is important as many MEDS datasets will not put all relevant properties in the "code" as the examples we've been seeing do. See https://github.com/mmcdermott/MEDS_transforms/issues/16 for the related MEDS transform issue.

**Comment by justin13601** [comment]
@mmcdermott Should we add some other notation to split the column name with the column value? Currently `BP//systolic` refers to `BP//systolic` in `code`, but maybe `col_A\\BP//systolic` will specify `BP//systolic` in `col_A`?

Or is it better to ask users to use `code//BP//systolic`, when referring to the `code` column, and otherwise it would be `col_A//BP//systolic` for the `col_A` column? I guess this can be generalized to just always take the first element as the col name and everything else as col value after splitting by `//`

**Comment by mmcdermott** [comment]
why not just have the column names be keys and the desired values values in the input dictionary? 

E.g., given
```yaml
  normal_spo2:
    code: lab_name//O2 saturation pulseoxymetry (%)
    value_min: 90
    value_max: 120
    value_min_inclusive: True
    value_max_inclusive: True
    other_col: foo
```

we can validate that `"other_col"` equals `"foo"`.

I think it is reasonable to limit the other validation to strings only for now, though we can also modify other aspects of the predicate syntax to allow us to specify ranges on other parameters as well.
